// src/components/Projects/Projects.vue
<script>
import { defineComponent } from 'vue'
import JsonData from "../Data/Projet.json";

export default defineComponent({
  data(){
    return{
      jsonWorks: JsonData,
      searchwork: null,
      jsonResultWork: null,
      githubResult: null
    }
  },
  methods:{
    searchWorks(){
      let searchInput = this.searchwork.toLowerCase();
      let filterArray = this.jsonWorks.project.filter(item => item.nameProject.toLowerCase().includes(searchInput))
      this.jsonResultWork = filterArray;
      if (this.jsonResultWork.length == 0) {
        console.log("https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley");
      }
    },
  },
  beforeUpdate(){
    this.searchWorks();
  }
})
</script>
<template>
  <div>
    <div class="worksWrapper" v-if="jsonResultWork == null ? works = jsonWorks.project : works = jsonResultWork">
      <div v-for="(projet, index) in works" v-bind:key="index" class="workCard">
        <router-link :to="{ name: 'Work', params: { name:projet.nameProject }}"><img :src="projet.imgProject" class="workImg" ></router-link>  
        <div class="workCards">
          <div class="workInformation">
            <h5 class="workTitle">{{projet.nameProject}}</h5>
            <p class="workDescription">{{projet.descriptionProject}}</p>
          </div>
          <div class="workInformation">
            <div class="workStack">
              <p v-for="(stack, index2) in projet.stackProject" v-bind:key="index2" class="stack">
                {{stack.stack1}}
                {{stack.stack2}}
                {{stack.stack3}}
                {{stack.stack4}}
                {{stack.stack5}}
              </p>
            </div>
            <p class="workTime">{{projet.timeProject}}</p>
            <div class="workBlock">
              <a v-if="projet.urlCodeProject != null" :href="projet.urlCodeProject" class="btnStyle" target="_blank">code</a>
              <a v-if="projet.urlSiteProject != null" :href="projet.urlSiteProject" class="btnStyle" target="_blank">url</a>
            </div>
          </div>
        </div>
      </div>
      <div v-if="jsonResultWork != null && jsonResultWork.length == 0" class="nullResult">
        <p>Aucun résultat pour "{{searchwork}}"</p>
        <p>Essayez de chercher autre chose ou Vérifiez l’orthographe du projet recherché. </p>
        <img src="@/assets/pouletoo.png" alt="">
      </div>
    </div>
  </div>
</template>

<style src="./Projects.css" scoped> </style>

// src/components/Projects/Projects.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import JsonData from "@/data/Projet.json";
import styles from "./Projects.module.css";

interface StackItem {
  stack1?: string;
  stack2?: string;
  stack3?: string;
  stack4?: string;
  stack5?: string;
}

interface Project {
  nameProject: string;
  descriptionProject: string;
  stackProject: StackItem[];
  imgProject: string;
  imgProject1: string;
  urlCodeProject?: string;
  urlSiteProject?: string;
  timeProject?: string;
}

export default function ProjectsComponent() {
  const [searchwork, setSearchwork] = useState("");
  const allProjects: Project[] = JsonData.project as Project[];

  const filteredProjects = searchwork
    ? allProjects.filter((item) =>
        item.nameProject.toLowerCase().includes(searchwork.toLowerCase())
      )
    : allProjects;

  return (
    <div>
      <div className={styles.worksWrapper}>
        {filteredProjects.map((projet, index) => (
          <div key={index} className={styles.workCard}>
            <Link href={`/work/${encodeURIComponent(projet.nameProject)}`}>
              <img src={projet.imgProject} className={styles.workImg} alt={projet.nameProject} />
            </Link>
            <div className={styles.workCards}>
              <div className={styles.workInformation}>
                <h5 className={styles.workTitle}>{projet.nameProject}</h5>
                <p className={styles.workDescription}>{projet.descriptionProject}</p>
              </div>
              <div className={styles.workInformation}>
                <div className={styles.workStack}>
                  {projet.stackProject.map((stack, index2) => (
                    <p key={index2} className={styles.stack}>
                      {stack.stack1}
                      {stack.stack2}
                      {stack.stack3}
                      {stack.stack4}
                      {stack.stack5}
                    </p>
                  ))}
                </div>
                {projet.timeProject && <p className={styles.workTime}>{projet.timeProject}</p>}
                <div className={styles.workBlock}>
                  {projet.urlCodeProject && (
                    <a href={projet.urlCodeProject} className={styles.btnStyle} target="_blank" rel="noopener noreferrer">code</a>
                  )}
                  {projet.urlSiteProject && (
                    <a href={projet.urlSiteProject} className={styles.btnStyle} target="_blank" rel="noopener noreferrer">url</a>
                  )}
                </div>
              </div>
            </div>
          </div>
        ))}
        {filteredProjects.length === 0 && searchwork && (
          <div className={styles.nullResult}>
            <p>Aucun résultat pour &quot;{searchwork}&quot;</p>
            <p>Essayez de chercher autre chose ou Vérifiez l&apos;orthographe du projet recherché.</p>
            <img src="/pouletoo.png" alt="" />
          </div>
        )}
      </div>
    </div>
  );
}
