// src/components/Skills/Skills.vue
<script>
import { defineComponent } from 'vue'
import Job from '../JsonData/DataJob.json'
import Stack from '../JsonData/DataStack.json'

export default defineComponent({
    setup() { },
    data(){
      return{
        Job:Job,
        Stack:Stack
      }
    }
})
</script>

<template>
  <div class="SkillsStackJob">
    <div class="exprerience">
      <h2 class="titleExprerience">Skills & Expérience</h2>
      <p>Je suis intéressé par le développement front-end et back-end.</p>
      <p>Je suis plus attiré par le front-end.</p>
      <p>J'utilise le plus souvent les framework Vue.js et Node.js .</p>
      <p>J'utilise aussi des framework comme Symfony et des cms comme Wordpress.</p>
      <p>Visitez mon profil <a href="https://www.linkedin.com/in/Renaudfradin/">Linkedin</a> pour plus de détails et mon <a href="https://github.com/Renaudfradin">Github</a> pour voir mes projets.</p>
    </div>
    <div class="StackJob">
      <div class="stackWrap">
        <div v-for="(stack , index) in Stack.Stack" v-bind:key="index">
          <img :src="stack.imgStack" alt="" srcset="" class="imgStack">
          <p class="titleStack">{{stack.titleStack}}</p>
        </div>
      </div>
      <div class="jobWrapper">
        <div v-for="(job , index) in Job.Job" v-bind:key="index">
          <h5 class="tileJob">{{job.titleJob}}</h5>
          <p>{{job.entrepriseJob}}</p>
          <p>{{job.dateJob}}</p>
          <p class="descriptionJob">{{job.descriptionJob}}</p>
          <p>{{job.typeJob}}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<style src="./Skill.css" scoped> </style>

// src/components/Skills/Skills.tsx
import JobData from "@/data/Job.json";
import StackData from "@/data/Stack.json";
import styles from "./Skills.module.css";

export default function SkillsComponent() {
  return (
    <div className={styles.SkillsStackJob}>
      <div className={styles.exprerience}>
        <h2 className={styles.titleExprerience}>Compétences &amp; Parcours</h2>
        <p>Développeur passionné, je me spécialise dans le back-end et l&apos;écosystème Laravel, tout en gardant un œil sur les dernières tendances du web.</p>
        <p>J&apos;aime créer des solutions performantes et sur-mesure avec Laravel, React.js et Node.js, en alliant technique et créativité.</p>
        <p>Curieux d&apos;en découvrir davantage ? Retrouvez mon parcours complet sur <a href="https://www.linkedin.com/in/Renaudfradin/">LinkedIn</a> ou explorez mes projets sur <a href="https://github.com/Renaudfradin">GitHub</a>.</p>
        <div className={styles.stackWrap}>
          {StackData.Stack.map((stack, index) => (
            <div key={index}>
              <img src={stack.imgStack} alt="" className={styles.imgStack} />
              <p className={styles.titleStack}>{stack.titleStack}</p>
            </div>
          ))}
        </div>
      </div>
      <div className={styles.StackJob}>
        <div className={styles.jobWrapper}>
          {JobData.Job.map((job, index) => (
            <div key={index}>
              <h5 className={styles.tileJob}>{job.titleJob}</h5>
              <p>{job.entrepriseJob}</p>
              <p>{job.dateJob}</p>
              <p>{job.typeJob}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
