// src/components/About/About.vue
<script>
import { defineComponent } from 'vue'

export default defineComponent({
  data(){
    return{
      dateResult: null
    }
  }
})
</script>

<template>
  <div class="presentationCard">
    <h3 class="presentationtitle">Présentation</h3>
    <p>Je suis un étudiant de 24 ans.</p>
    <p>Je suis actuellement en Mastère CTO & Tech Lead a l'école EEMI.</p>
    <p>J'ai obtenu un Bachelor développeur web à Hetic en septembre 2022.</p>
    <p>J'ai obtenu un BTS SIO (Service Informatique aux Organisations) SLAM (Solutions Logicielles et Applications Métiers) en juin 2020.</p>
    <p>J'ai obtenu un Titre professionnel Développeur web et web mobile à L'AFPA en juin 2019.</p>
    <p>J'ai obtenu mon baccalauréat STI2D (sciences & technologies de l'industrie et du développement durable) en juin 2018.</p>
    <p>Pendant mon temps libre je travaille sur des projet personelle , je fait du sport (c’est une passion et une motivation) , j'étudie aussi l’histoire et je joue aussi aux jeux vidéo.</p>
    <p>Je milite activement pour la cause animale.</p>
    <a href="cv/cv_renaud.pdf" download="CV_Renaud.pdf" class="btnCV">voir mon cv</a>
  </div>
</template>

<style src="./About.css" scoped> </style>

// src/components/About/About.tsx
import "./about.css";

export default function AboutComponent() {
  return (
    <div className="presentationCard">
      <h3 className="presentationtitle">Présentation</h3>
      <p>
        Développeur web passionné de 26 ans, je suis actuellement en CDI en tant
        que Full-Stack Developer.
      </p>
      <p>
        Diplômé d&apos;un Mastère CTO &amp; Tech Lead à l&apos;école EEMI,
        j&apos;ai également obtenu un Bachelor Développeur Web à HETIC, un BTS
        SIO SLAM, ainsi qu&apos;un Titre professionnel Développeur Web &amp; Web
        Mobile à l&apos;AFPA.
      </p>
      <p>
        J&apos;aime concevoir des solutions innovantes, apprendre en continu et
        relever de nouveaux défis techniques. Mon parcours m&apos;a permis
        d&apos;acquérir une solide expérience sur des projets variés, du
        back-end au front-end.
      </p>
      <p>
        En dehors du développement, je me passionne pour le sport,
        l&apos;histoire, la photographie, les jeux vidéo et je m&apos;investis
        activement pour la cause animale.
      </p>
      <a
        href="/cv/cv_renaud.pdf"
        download="CV_Renaud_Fradin.pdf"
        className="btnCV"
      >
        Voir mon CV
      </a>
    </div>
  );
}
