// webpack/src/components/Skills/Skills.vue
<template>
<div class="presentation">
  <h2 class="skills">Skills & Expérience</h2>
  <p class="metier">Je suis intéressé par le développement front-end et back-end.</p>
  <p class="metier">Je suis plus attiré par le front-end.</p>
  <p class="metier">J'utilise le plus souvent les framework Vue.js et Node.js .</p>
  <p class="metier">J'utilise aussi des framework comme Symfony et des cms comme Wordpress.</p>
  <p class="metier">Visitez mon profil <a href="https://www.linkedin.com/in/Renaudfradin/">Linkedin</a> pour plus de détails et mon <a href="https://github.com/Renaudfradin">Github</a> pour voir mes projets.</p>
</div>
</template>
<script>
import { defineComponent } from 'vue'
export default defineComponent({
  components:{ }
})
</script>
<style src="./Skills.css" scoped></style>

// src/pages/Skills.tsx
import Head from "next/head";
import styles from "@/styles/skills.module.css";

export default function skills() {
  return (
    <>
      <Head>
        <title>Skills</title>
        <meta
          name="Portfolio Renaud Fradin"
          content="Portfolio Renaud Fradin Développeur Fullstack"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>Skills page</p>
        <p>Skills & Expérience
          Je suis intéressé par le développement front-end.
          J'utilise le plus souvent les framework React.js , Vue.js et Node.js .
          J'utilise aussi des cms comme Wordpress et Webflow.
          Visitez mon profil Linkedin pour plus de détails et mon Github pour voir mes projets.
        </p>
      </div>
    </>
  )
}
