// src/components/Home/Home.vue
<script>
import { defineComponent } from 'vue'

export default defineComponent({
  setup() { },
})
</script>

<template>
  <div class="presentation">
    <h3>Bonjour</h3>
    <h3>Je suis Renaud</h3>
    <h3>Développeur Full-stack</h3>
    <div class="btnBlock">
      <router-link to="/projects" class="btnHome">Mes projets</router-link>
      <router-link to="/contact" class="btnHome">Contactez - moi !</router-link>
    </div>
  </div>    
</template>

<style src="./Home.css" scoped> </style>

// src/components/Home/Home.tsx
import Link from "next/link";
import styles from "./Home.module.css";

export default function HomeComponent() {
  return (
    <div className={styles.presentation}>
      <h3>Bonjour</h3>
      <h3>Je suis Renaud</h3>
      <h3>Développeur Full-stack</h3>
      <div className={styles.btnBlock}>
        <Link href="/projects" className={styles.btnHome}>Mes projets</Link>
        <Link href="/contact" className={styles.btnHome}>Contactez - moi !</Link>
      </div>
    </div>
  );
}
