// src/components/navbar.tsx
import Link from "next/link";
import Image from "next/image";
// import { items } from "./data";
import { Github, Linkedin, Home, User, Settings, Eye } from "lucide-react";

export default function navbar() {
  return ( 
    <div className="containerNav">
      <div>
        <Link href="/">
          <Image 
            src="../../assets/logo.svg"
            width={70}
            height={70}
            alt="logo"
          ></Image>
        </Link>
      </div>
      <div className="containerMenu">
        <Link href="/" className="iconNav">
          <Home color="white" size={30} strokeWidth={1.75} />
        </Link>
        <Link href="/about" className="iconNav">
          <User color="white" size={30} strokeWidth={1.75}/>
        </Link>
        <Link href="/skills" className="iconNav">
          <Settings color="white" size={30} strokeWidth={1.75}/>
        </Link>
        <Link href="/works" className="iconNav">
          <Eye color="white" size={30} strokeWidth={1.75}/>
        </Link>
      </div>
      <div className="containerResaux">
        <Link href="https://www.linkedin.com/in/renaudfradin/" replace target="_blank" className="iconNav">
          <Linkedin color="white" size={30} strokeWidth={1.75}/>
        </Link>
        <Link href="https://github.com/Renaudfradin" replace target="_blank" className="iconNav" >
          <Github color="white" size={30} strokeWidth={1.75}/>
        </Link>
      </div>
    </div>
  )
}

// src/components/NavBar/NavBar.vue
<script>
import { defineComponent } from 'vue'

export default defineComponent({
  setup() { },
  data(){
    return{
      urlLink:"https://www.linkedin.com/in/renaudfradin/",
      urlGit:"https://github.com/Renaudfradin"
    }
  }
})
</script>

<template>
  <div class="header">
    <div>
      <router-link class="nav1" to="/"><img class="nav3" style="width:100%" src="@/assets/logo.svg" alt=""></router-link>
    </div>
    <div>
      <router-link class="nav" to="/"><i class="fas fa-home"></i></router-link>
      <router-link class="nav" to="/About"><i class="far fa-user"></i></router-link>
      <router-link class="nav" to="/Skills"><i class="fas fa-cog"></i></router-link>
      <router-link class="nav" to="/Works"><i class="far fa-eye"></i></router-link>
      <router-link class="nav" to="/Contact"><i class="far fa-envelope"></i></router-link>
    </div>
    <div>
      <a class="nav" :href="urlLink" target="_blank"><i class="fab fa-linkedin-in"></i></a>
      <a class="nav" :href="urlGit" target="_blank"><i class="fab fa-github"></i></a>
    </div> 
  </div>
</template>

<style src="./NavBar.css" scoped> </style>
