// src/components/NavBar/NavBar.vue
<script>
import { defineComponent } from 'vue'

export default defineComponent({
  setup() { },
  data(){
    return{
      urlLink:"https://www.linkedin.com/in/renaudfradin/",
      urlGit:"https://github.com/Renaudfradin"
    }
  }
})
</script>

<template>
  <div class="header">
    <div>
      <router-link class="nav1" to="/"><img class="nav3" style="width:100%" src="@/assets/logo.svg" alt=""></router-link>
    </div>
    <div>
      <router-link class="nav" to="/" active-class="acticeClass"><i class="fas fa-home"></i></router-link>
      <router-link class="nav" to="/about" active-class="acticeClass"><i class="far fa-user"></i></router-link>
      <router-link class="nav" to="/skills" active-class="acticeClass"><i class="fas fa-cog"></i></router-link>
      <router-link class="nav" to="/projects" active-class="acticeClass"><i class="far fa-eye"></i></router-link>
      <router-link class="nav" to="/contact" active-class="acticeClass"><i class="far fa-envelope"></i></router-link>
    </div>
    <div>
      <a class="nav" :href="urlLink" target="_blank"><i class="fab fa-linkedin-in"></i></a>
      <a class="nav" :href="urlGit" target="_blank"><i class="fab fa-github"></i></a>
    </div> 
  </div>
</template>

<style src="./NavBar.css" scoped> </style>

// src/components/NavBar/NavBar.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import Image from "next/image";
import styles from "./NavBar.module.css";

export default function NavBar() {
  const pathname = usePathname();

  const urlLink = "https://www.linkedin.com/in/renaudfradin/";
  const urlGit = "https://github.com/Renaudfradin";

  return (
    <div className={styles.header}>
      <div>
        <Link className={styles.nav1} href="/">
          <img className={styles.nav3} style={{ width: "100%" }} src="/logo.svg" alt="Logo" />
        </Link>
      </div>
      <div>
        <Link className={`${styles.nav} ${pathname === "/" ? styles.activeClass : ""}`} href="/">
          <i className="fas fa-home"></i>
        </Link>
        <Link className={`${styles.nav} ${pathname === "/about" ? styles.activeClass : ""}`} href="/about">
          <i className="far fa-user"></i>
        </Link>
        <Link className={`${styles.nav} ${pathname === "/skills" ? styles.activeClass : ""}`} href="/skills">
          <i className="fas fa-cog"></i>
        </Link>
        <Link className={`${styles.nav} ${pathname === "/projects" ? styles.activeClass : ""}`} href="/projects">
          <i className="far fa-eye"></i>
        </Link>
        <Link className={`${styles.nav} ${pathname === "/contact" ? styles.activeClass : ""}`} href="/contact">
          <i className="far fa-envelope"></i>
        </Link>
      </div>
      <div>
        <a className={styles.nav} href={urlLink} target="_blank" rel="noopener noreferrer">
          <i className="fab fa-linkedin-in"></i>
        </a>
        <a className={styles.nav} href={urlGit} target="_blank" rel="noopener noreferrer">
          <i className="fab fa-github"></i>
        </a>
      </div>
    </div>
  );
}
