// src/components/Contact/Contact.tsx
import styles from "./Contact.module.css";

export default function ContactComponent() {
  return (
    <div className={styles.contactCard}>
      <h1 className={styles.contactTitle}>Travaillons ensemble&nbsp;!</h1>
      <p>Passionné par la création, je suis ouvert à tous types de projets — grands ou petits, chaque défi est une opportunité d&apos;innover.</p>
      <p>Disponible en freelance, je serais ravi de collaborer avec vous ou de répondre à vos questions. Contactez-moi par mail à <a href="mailto:renaudfradin@gmail.com" className={styles.contactLink}>renaudfradin@gmail.com</a> ou retrouvez-moi sur <a href="https://www.linkedin.com/in/Renaudfradin/" className={styles.contactLink} target="_blank" rel="noopener noreferrer"> LinkedIn</a></p>
    </div>
  );
}

// webpack/src/components/Contact/Contact.vue
<template>
<div class="presentation">
  <div class="presentation2">
    <h1 class="skills">Contactez moi</h1>
    <p class="metier">Je suis interessé par les grands ou petits projets : il n'y a que la création qui compte !</p>
    <p class="metier">Si vous avez des questions, n'hésitez pas à me contacter en utilisant mon adresse mail ou mon linkedin :</p>
    <p class="metier">renaudfradin@gmail.com</p>
    <p class="metier"><a href="https://www.linkedin.com/in/Renaudfradin/" target="_blank">Linkedin Renaud fradin</a></p>
  </div>
</div>
</template>
<script>
export default {
  name:'Contact',
  data(){
    return{
        infoform:false, 
    }
  },
}
</script>
<style src="./Contact.css" scoped> </style>
