// src/components/Work/Work.vue
<script>
import { defineComponent } from 'vue'
import JsonData from "../Data/Projet.json";

export default defineComponent({
  data(){
    return{
      jsonWorks: JsonData
    }
  }
})
</script>

<template>
    <div v-for="(projects , index) in jsonWorks.project" v-bind:key="index" class="cardWork"> 
      <div v-if="projects.nameProject == $route.params.name" >
        <h3 class="titleWork">{{projects.nameProject}}</h3> 
        <img class="imgWork" :src="projects.imgProject1" >
        <p class="descriptionWork">{{projects.descriptionProject}}</p>
        <div class="stackWork">
          <p v-for="(stack , index2) in projects.stackProject" v-bind:key="index2" class="stack">
            {{stack.stack1}}
            {{stack.stack2}}
            {{stack.stack3}}
            {{stack.stack4}}
            {{stack.stack5}}
          </p>
        </div>
        <div class="Workbtn">
          <a v-if="projects.urlCodeProject != null" :href="projects.urlCodeProject" class="btnWork" target="_blank">code</a>
          <a v-if="projects.urlSiteProject != null" :href="projects.urlSiteProject" class="btnWork" target="_blank">site</a>
        </div>
      </div>
  </div>
</template>

<style src="./Work.css" scoped> </style>

// src/components/Work/Work.tsx
import JsonData from "@/data/Projet.json";
import styles from "./Work.module.css";

interface StackItem {
  stack1?: string;
  stack2?: string;
  stack3?: string;
  stack4?: string;
  stack5?: string;
}

interface Project {
  nameProject: string;
  descriptionProject: string;
  stackProject: StackItem[];
  imgProject: string;
  imgProject1: string;
  urlCodeProject?: string;
  urlSiteProject?: string;
}

export default function WorkComponent({ name }: { name: string }) {
  const project = (JsonData.project as Project[]).find(
    (p) => p.nameProject === name
  );

  if (!project) {
    return (
      <div className={styles.cardWork}>
        <h3 className={styles.titleWork}>Projet non trouvé</h3>
      </div>
    );
  }

  return (
    <div className={styles.cardWork}>
      <h3 className={styles.titleWork}>{project.nameProject}</h3>
      <img className={styles.imgWork} src={project.imgProject1} alt={project.nameProject} />
      <p className={styles.descriptionWork}>{project.descriptionProject}</p>
      <div className={styles.stackWork}>
        {project.stackProject.map((stack, index) => (
          <p key={index} className={styles.stack}>
            {stack.stack1}
            {stack.stack2}
            {stack.stack3}
            {stack.stack4}
            {stack.stack5}
          </p>
        ))}
      </div>
      <div className={styles.Workbtn}>
        {project.urlCodeProject && (
          <a href={project.urlCodeProject} className={styles.btnWork} target="_blank" rel="noopener noreferrer">code</a>
        )}
        {project.urlSiteProject && (
          <a href={project.urlSiteProject} className={styles.btnWork} target="_blank" rel="noopener noreferrer">site</a>
        )}
      </div>
    </div>
  );
}
